import { useEffect, useState } from 'react'
import { useFieldArray, useForm } from 'react-hook-form'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ApiError, apiFetch } from '../../api/http'
import type { Customer, LineItem, WorkOrder } from '../../api/types'
import { useSession } from '../../auth/SessionContext'
import { useOnline } from '../../offline/OnlineState'
import { cacheCustomers, cachedCustomers, cacheOrders, cachedOrder } from '../../offline/db'
import { AttachmentPanel } from '../files/AttachmentPanel'

type FormValues = {customer_id:string; location_id:string; status:string; priority:string; received_date:string; due_date:string; assigned_to:string; delivery_method:string; po_number:string; description:string; production_notes:string; customer_notes:string; tax_rate:number; deposit:number; discount:number; items:LineItem[]}
const today=()=>new Date().toISOString().slice(0,10)

export function OrderEditor() {
  const {id}=useParams(); const editing=Boolean(id&&id!=='new'); const navigate=useNavigate(); const {session}=useSession(); const {online}=useOnline(); const [version,setVersion]=useState(0); const [error,setError]=useState(''); const [conflict,setConflict]=useState<WorkOrder|null>(null); const [offlineOrder,setOfflineOrder]=useState<WorkOrder|null>(null); const [deleting,setDeleting]=useState(false)
  const [customerRows,setCustomers]=useState<Customer[]>([])
  const {register,control,handleSubmit,reset,watch,formState:{isSubmitting}}=useForm<FormValues>({defaultValues:{customer_id:'',location_id:session?.location.id??'',status:'New',priority:'Normal',received_date:today(),due_date:'',assigned_to:'',delivery_method:'Pickup',po_number:'',description:'',production_notes:'',customer_notes:'',tax_rate:0,deposit:0,discount:0,items:[{item_name:'',quantity:1,unit_price:0}]}})
  const fields=useFieldArray({control,name:'items'})
  useEffect(()=>{if(!online){if(editing&&id)void cachedOrder(id).then(x=>setOfflineOrder(x??null));return}void cachedCustomers().then(rows=>{if(rows.length)setCustomers(rows)});void apiFetch<{customers:Customer[]}>('/api/customers?limit=200').then(async x=>{setCustomers(x.customers);await cacheCustomers(x.customers)});if(editing)void apiFetch<WorkOrder>(`/api/orders/${id}`).then(async o=>{setVersion(o.version);reset(o);await cacheOrders([o])}).catch(e=>setError(e instanceof Error?e.message:'Unable to load order'))},[editing,id,reset,online])
  const items=watch('items'); const subtotal=(items??[]).reduce((sum,x)=>sum+(Number(x.quantity)||0)*(Number(x.unit_price)||0),0)
  const submit=handleSubmit(async values=>{setError('');setConflict(null);try{const saved=editing?await apiFetch<WorkOrder>(`/api/orders/${id}`,{method:'PATCH',body:JSON.stringify({...values,version})}):await apiFetch<WorkOrder>('/api/orders',{method:'POST',body:JSON.stringify(values)});await cacheOrders([saved]);navigate(`/orders/${saved.id}`)}catch(e){if(e instanceof ApiError&&e.status===409){setConflict(e.current as WorkOrder);setError('This work order changed on another device. Review the current server version before trying again.')}else setError(e instanceof Error?e.message:'Save failed')}})
  async function remove(){if(!editing||!id||!window.confirm('Delete this work order?'))return;setDeleting(true);setError('');try{await apiFetch(`/api/orders/${id}`,{method:'DELETE',body:JSON.stringify({version})});navigate('/orders')}catch(e){setError(e instanceof Error?e.message:'Delete failed')}finally{setDeleting(false)}}
  if(!online){if(!editing)return <section><div className="page-heading"><h1>New work order</h1></div><div className="panel muted">Creating work orders is unavailable offline.</div></section>;if(!offlineOrder)return <section><div className="page-heading"><h1>Work order</h1></div><div className="panel muted">This order is not available in the local cache.</div></section>;const o=offlineOrder;return <section><div className="page-heading"><div><h1>{o.order_number}</h1><p className="muted">Cached read-only copy</p></div><Link className="button secondary" to="/orders">Back</Link></div><div className="panel detail-grid"><div><span>Status</span><strong>{o.status}</strong></div><div><span>Priority</span><strong>{o.priority}</strong></div><div><span>Due</span><strong>{o.due_date||'—'}</strong></div><div><span>Total / Balance</span><strong>${o.total.toFixed(2)} / ${o.balance.toFixed(2)}</strong></div><div className="span-2"><span>Description</span><strong>{o.description||'—'}</strong></div></div><div className="panel table-wrap"><table><thead><tr><th>Item</th><th>Qty</th><th>Unit</th></tr></thead><tbody>{o.items.map((x,i)=><tr key={i}><td>{String(x.item_name??x.description??'Item')}</td><td>{x.quantity}</td><td>${Number(x.unit_price).toFixed(2)}</td></tr>)}</tbody></table></div></section>}
  return <section><div className="page-heading"><div><h1>{editing?'Work order':'New work order'}</h1>{editing&&<p className="muted">Version {version}</p>}</div>{editing&&<div className="button-row"><Link className="button secondary" to={`/orders/${id}/print`}>Print ticket</Link>{(session?.employee.role==='supervisor'||session?.employee.role==='admin')&&<button type="button" className="danger" onClick={()=>void remove()} disabled={deleting}>{deleting?'Deleting…':'Delete work order'}</button>}</div>}</div>
    {conflict&&<div className="conflict-banner"><strong>Server version {conflict.version}</strong><span>Status: {conflict.status}; due {conflict.due_date||'not set'}.</span><button onClick={()=>{setVersion(conflict.version);reset(conflict);setConflict(null);setError('')}}>Load server version</button></div>}
    <form onSubmit={submit} className="form-stack"><div className="panel form-grid"><label>Customer<select {...register('customer_id',{required:true})}><option value="">Choose customer…</option>{customerRows.map(c=><option key={c.id} value={c.id}>{c.company||`${c.first_name} ${c.last_name}`}</option>)}</select></label><label>Store<select {...register('location_id',{required:true})}>{(session?.employee.role==='admin'?session.locations:[session?.location].filter(Boolean)).map(loc=><option key={loc!.id} value={loc!.id}>{loc!.name} #{loc!.store_number}</option>)}</select></label><label>Status<select {...register('status')} >{['Quote','New','Awaiting Artwork','Proof Sent','Proof Approved','In Production','Ready for Pickup','Completed','On Hold','Cancelled'].map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select {...register('priority')}><option>Normal</option><option>High</option><option>Rush</option></select></label><label>Received<input type="date" {...register('received_date')} /></label><label>Due<input type="date" {...register('due_date')} /></label><label>Assigned to<input {...register('assigned_to')} /></label><label>Delivery<select {...register('delivery_method')}><option>Pickup</option><option>Delivery</option><option>Ship</option></select></label><label>PO number<input {...register('po_number')} /></label><label className="span-2">Description<input {...register('description')} /></label></div>
      <div className="panel"><div className="section-heading"><h2>Line items</h2><button type="button" className="secondary" onClick={()=>fields.append({item_name:'',quantity:1,unit_price:0})}>Add item</button></div>{fields.fields.map((field,index)=><div className="line-item" key={field.id}><input placeholder="Item / service" {...register(`items.${index}.item_name` as const)} /><input aria-label="Quantity" min="0" type="number" step="0.01" {...register(`items.${index}.quantity` as const,{valueAsNumber:true})}/><input aria-label="Unit price" min="0" type="number" step="0.01" {...register(`items.${index}.unit_price` as const,{valueAsNumber:true})}/><button type="button" className="danger-link" onClick={()=>fields.remove(index)}>Remove</button></div>)}<p className="totals-preview">Item subtotal preview: <strong>${subtotal.toFixed(2)}</strong> <span className="muted">Final totals are calculated by the server.</span></p></div>
      <div className="panel form-grid"><label>Tax %<input min="0" type="number" step="0.0001" {...register('tax_rate',{valueAsNumber:true})}/></label><label>Discount<input min="0" type="number" step="0.01" {...register('discount',{valueAsNumber:true})}/></label><label>Deposit<input min="0" type="number" step="0.01" {...register('deposit',{valueAsNumber:true})}/></label><label className="span-2">Production notes<textarea rows={4} {...register('production_notes')}/></label><label className="span-2">Customer notes<textarea rows={3} {...register('customer_notes')}/></label></div>
      {editing&&id&&<AttachmentPanel orderId={id}/>} {error&&<p className="error">{error}</p>}<div className="form-actions"><button disabled={isSubmitting}>{isSubmitting?'Saving…':'Save work order'}</button><button type="button" className="secondary" onClick={()=>navigate('/orders')}>Cancel</button></div>
    </form></section>
}
