import { expect, test, type Page } from '@playwright/test'

async function signIn(page:Page,employee='Test Admin',pin='246810'){
 await page.goto('/')
 await page.getByLabel('Company code').fill('TEST-PRINT')
 await page.getByLabel('Company password').fill('company-password')
 await page.getByRole('button',{name:'Continue'}).click()
 await page.getByRole('combobox',{name:'Store',exact:true}).selectOption({label:'Sayville #5127'})
 await page.getByRole('combobox',{name:'Employee',exact:true}).selectOption({label:employee})
 await page.getByLabel('PIN',{exact:true}).fill(pin)
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Main Dashboard',exact:true})).toBeVisible()
}

test('customer issues support manual logs, follow-up, resolve and reopen across stores',async({page,context})=>{
 const unique=Date.now().toString();const customerName=`Case customer ${unique}`;const title=`Wrong package ${unique}`
 await signIn(page)
 await page.getByRole('link',{name:'Customers',exact:true}).click()
 await page.getByRole('link',{name:'New customer',exact:true}).click()
 await page.getByLabel('Company',{exact:true}).fill(customerName)
 await page.getByLabel('Phone',{exact:true}).fill('555-0100')
 await page.getByRole('button',{name:'Save customer',exact:true}).click()
 await expect(page).toHaveURL(/\/customers\/[0-9a-f-]{36}$/)
 await page.getByRole('link',{name:'Customer Issues',exact:true}).click()
 await page.getByRole('link',{name:'New case',exact:true}).click()
 await page.getByRole('combobox',{name:'Customer',exact:true}).selectOption({label:customerName})
 await page.getByLabel('Case title',{exact:true}).fill(title)
 await page.getByLabel('Issue description',{exact:true}).fill('Customer received a package belonging to another person.')
 await page.getByRole('combobox',{name:'Category',exact:true}).selectOption('Shipping')
 await page.getByRole('combobox',{name:'Priority',exact:true}).selectOption('Urgent')
 await page.getByRole('button',{name:'Save case',exact:true}).click()
 await expect(page).toHaveURL(/\/issues\/[0-9a-f-]{36}$/)
 const caseUrl=page.url()
 await page.getByRole('combobox',{name:'Communication channel',exact:true}).selectOption('phone')
 await page.getByLabel('Communication summary').fill('Called customer; return arranged.')
 await page.getByLabel('Update next action and follow-up with this log').check()
 await page.getByLabel('Next action after communication').fill('Confirm package returned')
 await page.getByLabel('Next follow-up date').fill('2026-10-06')
 await page.getByRole('button',{name:'Log communication',exact:true}).click()
 await expect(page.getByText('Called customer; return arranged.',{exact:true})).toBeVisible()
 await expect(page.getByRole('textbox',{name:'Next action',exact:true})).toHaveValue('Confirm package returned')
 await page.getByLabel('Resolution summary').fill('Package returned to correct customer')
 await page.getByRole('button',{name:'Resolve case',exact:true}).click()
 await expect(page.getByRole('button',{name:'Reopen case',exact:true})).toBeVisible()
 await page.getByLabel('Reason for reopening').fill('Customer requested another update')
 await page.getByRole('button',{name:'Reopen case',exact:true}).click()
 await expect(page.getByRole('button',{name:'Resolve case',exact:true})).toBeVisible()
 await page.getByRole('combobox',{name:'Active store',exact:true}).selectOption({label:'Selden #5345'})
 await expect(page).toHaveURL(/\/$/)
 await page.goto(caseUrl)
 await expect(page.getByLabel('Case title')).toHaveValue(title)
 // Administrator has cross-store write rights; an ordinary employee requires the active store.
 const session=await (await page.request.get('/api/web/session')).json()
 const staffName=`Issue Staff ${unique}`
 const staff=await page.request.post('/api/admin/employees',{headers:{'X-CSRF-Token':session.csrf_token},data:{name:staffName,pin:'135790',role:'employee',location_ids:session.locations.map((x:{id:string})=>x.id)}})
 expect(staff.ok()).toBeTruthy()
 await page.getByRole('button',{name:'Sign out',exact:true}).click()
 await signIn(page,staffName,'135790')
 await page.getByRole('combobox',{name:'Active store',exact:true}).selectOption({label:'Selden #5345'})
 await expect(page).toHaveURL(/\/$/)
 await page.goto(caseUrl)
 await expect(page.getByRole('button',{name:'Save case',exact:true})).toBeDisabled()
 await expect(page.getByText(/Switch to Sayville to update/)).toBeVisible()
 await page.getByRole('combobox',{name:'Active store',exact:true}).selectOption({label:'Sayville #5127'})
 await expect(page).toHaveURL(/\/$/)
 await page.goto(caseUrl)
 await expect(page.getByRole('button',{name:'Save case',exact:true})).toBeEnabled()
 await page.setViewportSize({width:390,height:844})
 await expect(page.getByRole('link',{name:'Customer Issues',exact:true})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
 await context.setOffline(true)
 await expect(page.getByRole('button',{name:'Save case',exact:true})).toBeDisabled()
 await context.setOffline(false)
 await page.getByRole('button',{name:'Sign out',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Store Operations Hub',exact:true})).toBeVisible()
 await page.goto(caseUrl)
 await expect(page.getByRole('heading',{name:'Store Operations Hub',exact:true})).toBeVisible()
 await expect(page.getByLabel('Case title')).toHaveCount(0)
})
