import { useEffect, useState } from 'react'
import { useForm } from 'react-hook-form'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { apiFetch, ApiError } from '../../api/http'
import type { Customer } from '../../api/types'
import { useSession } from '../../auth/SessionContext'
import { useOnline } from '../../offline/OnlineState'
import { cacheCustomers, cachedCustomer } from '../../offline/db'

type FormValues = Pick<Customer,'company'|'first_name'|'last_name'|'phone'|'email'|'address1'|'address2'|'city'|'state'|'postal_code'|'notes'> & { tax_exempt:boolean }
const defaults: FormValues = { company:'',first_name:'',last_name:'',phone:'',email:'',address1:'',address2:'',city:'',state:'',postal_code:'',notes:'',tax_exempt:false }

export function CustomerEditor() {
  const { id } = useParams(); const editing = Boolean(id && id !== 'new'); const navigate = useNavigate(); const {online}=useOnline(); const {session}=useSession()
  const [version,setVersion]=useState(0); const [error,setError]=useState(''); const [conflict,setConflict]=useState<Customer|null>(null); const [deleting,setDeleting]=useState(false); const [offlineRow,setOfflineRow]=useState<Customer|null>(null)
  const { register, handleSubmit, reset, formState:{isSubmitting} } = useForm<FormValues>({defaultValues:defaults})
  useEffect(() => { if(!editing||!id)return;if(!online){void cachedCustomer(id).then(x=>setOfflineRow(x??null));return}void apiFetch<Customer>(`/api/customers/${id}`).then(async c => { setVersion(c.version); reset(c); await cacheCustomers([c]) }).catch(e => setError(e instanceof Error ? e.message : 'Unable to load customer')) }, [id,editing,reset,online])
  const submit = handleSubmit(async values => { setError(''); setConflict(null); try { const saved = editing ? await apiFetch<Customer>(`/api/customers/${id}`,{method:'PATCH',body:JSON.stringify({...values,version})}) : await apiFetch<Customer>('/api/customers',{method:'POST',body:JSON.stringify(values)}); setVersion(saved.version); reset(saved); await cacheCustomers([saved]); navigate(`/customers/${saved.id}`) } catch(e) { if(e instanceof ApiError && e.status===409 && e.current){setConflict(e.current as Customer);setError('This customer changed on another device. Review the server copy before saving again.')}else setError(e instanceof Error ? e.message : 'Save failed') } })
  async function remove(){ if(!editing||!id||!window.confirm('Delete this customer?'))return; setDeleting(true); setError(''); try{await apiFetch(`/api/customers/${id}`,{method:'DELETE',body:JSON.stringify({version})});navigate('/customers')}catch(e){setError(e instanceof Error?e.message:'Delete failed')}finally{setDeleting(false)} }
  if(!online){if(!editing)return <section><div className="page-heading"><h1>New customer</h1></div><div className="panel muted">Creating customers is unavailable offline.</div></section>;if(!offlineRow)return <section><div className="page-heading"><h1>Customer</h1></div><div className="panel muted">This customer is not available in the local cache.</div></section>;return <section><div className="page-heading"><div><h1>{offlineRow.company||`${offlineRow.first_name} ${offlineRow.last_name}`.trim()||'Customer'}</h1><p className="muted">Cached read-only copy</p></div><Link className="button secondary" to="/customers">Back</Link></div><div className="panel detail-grid"><div><span>Contact</span><strong>{`${offlineRow.first_name} ${offlineRow.last_name}`.trim()||'—'}</strong></div><div><span>Phone</span><strong>{offlineRow.phone||'—'}</strong></div><div><span>Email</span><strong>{offlineRow.email||'—'}</strong></div><div><span>Address</span><strong>{[offlineRow.address1,offlineRow.address2,offlineRow.city,offlineRow.state,offlineRow.postal_code].filter(Boolean).join(', ')||'—'}</strong></div></div></section>}
  return <section><div className="page-heading"><div><h1>{editing?'Edit customer':'New customer'}</h1>{editing&&<p className="muted">Version {version}</p>}</div><Link className="button secondary" to="/customers">Back to customers</Link></div>
    {conflict&&<div className="conflict-banner"><strong>Server version {conflict.version}</strong><span>{conflict.company||`${conflict.first_name} ${conflict.last_name}`.trim()||'Customer'}</span><button type="button" onClick={()=>{setVersion(conflict.version);reset(conflict);setConflict(null);setError('')}}>Load server version</button></div>}
    <form className="panel form-grid" onSubmit={submit}>
      <label>Company<input {...register('company')} /></label><label>First name<input {...register('first_name')} /></label><label>Last name<input {...register('last_name')} /></label><label>Phone<input {...register('phone')} /></label><label>Email<input type="email" {...register('email')} /></label><label>Address<input {...register('address1')} /></label><label>Address 2<input {...register('address2')} /></label><label>City<input {...register('city')} /></label><label>State<input {...register('state')} /></label><label>ZIP<input {...register('postal_code')} /></label><label className="checkbox"><input type="checkbox" {...register('tax_exempt')} /> Tax exempt</label><label className="span-2">Notes<textarea rows={4} {...register('notes')} /></label>
      {error&&<p className="error span-2">{error}</p>}<div className="form-actions span-2"><div>{editing&&(session?.employee.role==='supervisor'||session?.employee.role==='admin')&&<button type="button" className="danger" onClick={()=>void remove()} disabled={deleting}>{deleting?'Deleting…':'Delete customer'}</button>}</div><div className="button-row"><button disabled={isSubmitting}>{isSubmitting?'Saving…':'Save customer'}</button><button type="button" className="secondary" onClick={()=>navigate(-1)}>Cancel</button></div></div>
    </form></section>
}
